=== ansys/ansys-pyetk/src/ansys/aedt/toolkits/electronic_transformer/backend/schemas/pyetk_schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/pyetk",
  "definitions": {
    "pyetk": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "json_version": {
          "$ref": "#/definitions/JsonVersion"
        },
        "core": {
          "$ref": "#/definitions/Core"
        },
        "bobbin": {
          "$ref": "#/definitions/Bobbin"
        },
        "winding": {
          "$ref": "#/definitions/Winding"
        },
        "circuit": {
          "$ref": "#/definitions/Circuit"
        },
        "settings": {
          "$ref": "#/definitions/Settings"
        },
        "materials": {
          "$ref": "#/definitions/Materials"
        }
      },
      "required": [
        "bobbin",
        "circuit",
        "core",
        "settings",
        "json_version",
        "winding"
      ],
      "title": "PyETK Main Configuration"
    },
    "JsonVersion": {
      "json_version": {
        "type": "object"
      }
    },
    "Bobbin": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "draw_bobbin": {
          "type": "boolean"
        },
        "board_thickness": {
          "type": "number"
        },
        "material": {
          "type": "string"
        }
      },
      "required": [
        "board_thickness",
        "draw_bobbin",
        "material"
      ],
      "title": "Bobbin"
    },
    "Circuit": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "connections": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/Connection"
          }
        },
        "side_loads": {
          "type": "array",
          "items": {
            "type": "number"
          }
        },
        "excitation": {
          "$ref": "#/definitions/Excitation"
        }
      },
      "required": [
        "connections",
        "excitation",
        "side_loads"
      ],
      "title": "Circuit"
    },
    "Connection": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^[0-9]+$": {
          "oneOf": [
            {
              "type": "string",
              "const": "Layer"
            },
            {
              "type": "object",
              "additionalProperties": {
                "oneOf": [
                  {
                    "type": "string",
                    "const": "Layer"
                  },
                  {
                    "$ref": "#/definitions/Connection"
                  }
                ]
              }
            }
          ]
        },
        "^[PS][0-9]+$": {
          "type": "object",
          "additionalProperties": {
            "oneOf": [
              {
                "type": "string",
                "const": "Layer"
              },
              {
                "$ref": "#/definitions/Connection"
              }
            ]
          }
        }
      },
      "required": [],
      "title": "Connection"
    },
    "Excitation": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "value": {
          "type": "number"
        }
      },
      "required": [
        "type",
        "value"
      ],
      "title": "Excitation"
    },
    "Core": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "supplier": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "model": {
          "type": "string"
        },
        "material": {
          "type": "string"
        },
        "dimensions": {
          "$ref": "#/definitions/Dimensions"
        },
        "airgap": {
          "$ref": "#/definitions/Airgap"
        }
      },
      "required": [
        "airgap",
        "dimensions",
        "material",
        "model",
        "supplier",
        "type"
      ],
      "title": "Core"
    },
    "Airgap": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "define_airgap": {
          "type": "boolean"
        },
        "airgap_on_leg": {
          "type": "string"
        },
        "airgap_value": {
          "type": "number"
        }
      },
      "required": [
        "define_airgap"
      ],
      "title": "Airgap"
    },
    "Dimensions": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "D_1": {
          "type": "number"
        },
        "D_2": {
          "type": "number"
        },
        "D_3": {
          "type": "number"
        },
        "D_4": {
          "type": "number"
        },
        "D_5": {
          "type": "number"
        },
        "D_6": {
          "type": "number"
        },
        "D_7": {
          "type": "number"
        },
        "D_8": {
          "type": "number"
        }
      },
      "required": [
        "D_1",
        "D_2",
        "D_3",
        "D_4",
        "D_5",
        "D_6",
        "D_7",
        "D_8"
      ],
      "title": "Dimensions"
    },
    "Materials": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^.*$": {
          "$ref": "#/definitions/MaterialProperties"
        }
      },
      "required": [
      ],
      "title": "Materials"
    },
    "MaterialProperties": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "conductivity": {
          "type": "number"
        },
        "power_ferrite_loss_params": {
          "$ref": "#/definitions/PowerFerriteLossParams"
        },
        "density": {
          "type": "number"
        },
        "mur": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "number"
            }
          ]
        },
        "epsr": {
          "type": "number"
        },
        "mu_vs_freq": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "number"
            }
          }
        }
      },
      "required": [
      ],
      "title": "Material Property Structure"
    },
    "PowerFerriteLossParams": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "cm": {
          "type": "number"
        },
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "required": [
        "cm",
        "x",
        "y"
      ],
      "title": "PowerFerriteLossParams"
    },
    "Settings": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "full_model": {
          "type": "boolean"
        },
        "region_offset": {
          "type": "number"
        },
        "segmentation_angle": {
          "type": "number"
        },
        "core_segments": {
          "type": "integer"
        },
        "conductor_segments": {
          "type": "integer" },
        "analysis_setup": {
          "$ref": "#/definitions/AnalysisSetup"
        }
      },
      "required": [
        "analysis_setup",
        "full_model",
        "region_offset",
        "segmentation_angle"
      ],
      "title": "Settings"
    },
    "AnalysisSetup": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "adaptive_frequency": {
          "type": "number"
        },
        "percentage_error": {
          "type": "number"
        },
        "number_passes": {
          "type": "integer"
        },
        "frequency_sweep": {
          "$ref": "#/definitions/FrequencySweep"
        }
      },
      "required": [
        "adaptive_frequency",
        "frequency_sweep",
        "number_passes",
        "percentage_error"
      ],
      "title": "AnalysisSetup"
    },
    "FrequencySweep": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "frequency_sweep": {
          "type": "boolean"
        },
        "start_frequency": {
          "type": "number"
        },
        "stop_frequency": {
          "type": "number"
        },
        "samples": {
          "type": "integer"
        },
        "scale": {
          "type": "string"
        },
        "start_frequency_unit": {
          "type": "string"
        },
        "stop_frequency_unit": {
          "type": "string"
        }
      },
      "required": [
        "frequency_sweep"
      ],
      "title": "FrequencySweep"
    },
    "Winding": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "layer_type": {
          "type": "string"
        },
        "layer_spacing": {
          "type": "number"
        },
        "top_margin": {
          "type": "number"
        },
        "side_margin": {
          "type": "number"
        },
        "layers": {
          "$ref": "#/definitions/Layers"
        }
      },
      "required": [
        "layer_spacing",
        "layer_type",
        "layers",
        "side_margin",
        "top_margin"
      ],
      "title": "Winding"
    },
    "Layers": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": {
        "^layer_[0-9]*": {
          "$ref": "#/definitions/Layer"
        }
      },
      "required": [
      ],
      "title": "Layers"
    },
    "Layer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "conductor": {
          "$ref": "#/definitions/Conductor"
        },
        "insulation": {
          "$ref": "#/definitions/Insulation"
        },
        "turns": {
          "$ref": "#/definitions/Turns"
        },
          "segments_number": {
            "type": "integer"
          }
      },
      "required": [
        "conductor",
        "turns"
      ],
      "title": "Layer"
    },
    "Conductor": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "draw_skin_layers": {
          "type": "boolean"
        },
        "material": {
          "type": "string"
        },
        "width": {
          "type": "number"
        },
        "diameter": {
          "type": "number"
        },
        "height": {
          "type": "number"
        },
        "type": {
          "type": "string"
        }
      },
      "required": [
        "draw_skin_layers",
        "material",
        "type"
      ],
      "oneOf": [
        {
          "properties": {
            "type": {
              "const": "Circular"
            }
          },
          "required": [
            "diameter"
          ]
        },
        {
          "properties": {
            "type": {
              "const": "Rectangular"
            }
          },
          "required": [
            "width",
            "height"
          ]
        }
      ],
      "title": "Conductor"
    },
    "Insulation": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "thickness": {
          "type": "number"
        },
        "material": {
          "type": "string"
        }
      },
      "required": [
        "material",
        "thickness"
      ],
      "title": "Insulation"
    },
    "Turns": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "quantity": {
          "type": "integer"
        },
        "spacing": {
          "type": "string"
        },
        "distance": {
          "type": "number"
        }
      },
      "required": [
        "quantity",
        "spacing",
        "distance"
      ],
      "title": "Turns"
    }
  }
}

=== ansys/ansys-pyetk/tests/frontend/versioned_json/v0_1_0/EI_planar_rectangular.json
{
  "json_version": "0.1.0",
  "core": {
    "supplier": "Ferroxcube",
    "type": "EI",
    "model": "E14/3.5/5R",
    "material": "3F3",
    "dimensions": {
      "D_1": 14.0,
      "D_2": 11.0,
      "D_3": 3.0,
      "D_4": 3.66,
      "D_5": 2.16,
      "D_6": 5.0,
      "D_7": 0.8,
      "D_8": 1.8
    },
    "airgap": {
      "define_airgap": false,
      "airgap_on_leg": "None",
      "airgap_value": 0.0
    }
  },
  "winding": {
    "layer_type": "Planar",
    "layer_spacing": 0.0,
    "top_margin": 0.0,
    "side_margin": 0.0,
    "layers": {
      "layer_1": {
        "conductor": {
          "draw_skin_layers": true,
          "material": "Copper",
          "type": "Rectangular",
          "width": 0.178,
          "height": 0.07
        },
        "turns": {
          "quantity": 7,
          "spacing": "top",
          "distance": 0.3
        },
        "segments_number": 8
      },
      "layer_2": {
        "conductor": {
          "draw_skin_layers": true,
          "material": "Copper",
          "type": "Rectangular",
          "width": 0.178,
          "height": 0.07
        },
        "turns": {
          "quantity": 7,
          "spacing": "top",
          "distance": 0.3
        },
        "segments_number": 8
      },
      "layer_3": {
        "conductor": {
          "draw_skin_layers": true,
          "material": "Copper",
          "type": "Rectangular",
          "width": 0.81,
          "height": 0.07
        },
        "turns": {
          "quantity": 3,
          "spacing": "top",
          "distance": 0.3
        },
        "segments_number": 8
      },
      "layer_4": {
        "conductor": {
          "draw_skin_layers": true,
          "material": "Copper",
          "type": "Rectangular",
          "width": 1.37,
          "height": 0.07
        },
        "turns": {
          "quantity": 2,
          "spacing": "top",
          "distance": 0.3
        },
        "segments_number": 8
      },
      "layer_5": {
        "conductor": {
          "draw_skin_layers": true,
          "material": "Copper",
          "type": "Rectangular",
          "width": 1.37,
          "height": 0.07
        },
        "turns": {
          "quantity": 2,
          "spacing": "top",
          "distance": 0.3
        },
        "segments_number": 8
      },
      "layer_6": {
        "conductor": {
          "draw_skin_layers": true,
          "material": "Copper",
          "type": "Rectangular",
          "width": 0.81,
          "height": 0.07
        },
        "turns": {
          "quantity": 3,
          "spacing": "top",
          "distance": 0.3
        },
        "segments_number": 8
      },
      "layer_7": {
        "conductor": {
          "draw_skin_layers": true,
          "material": "Copper",
          "type": "Rectangular",
          "width": 0.178,
          "height": 0.07
        },
        "turns": {
          "quantity": 7,
          "spacing": "top",
          "distance": 0.3
        },
        "segments_number": 8
      },
      "layer_8": {
        "conductor": {
          "draw_skin_layers": true,
          "material": "Copper",
          "type": "Rectangular",
          "width": 0.178,
          "height": 0.07
        },
        "turns": {
          "quantity": 7,
          "spacing": "top",
          "distance": 0.3
        },
        "segments_number": 8
      }
    }
  },
  "bobbin": {
    "draw_bobbin": true,
    "board_thickness": 0.2,
    "material": "material_bobbin"
  },
  "circuit": {
    "connections": {
      "4": {
        "P5": {
          "1": "Layer",
          "8": "Layer"
        }
      },
      "1": {
        "P2": {
          "2": "Layer",
          "7": "Layer"
        }
      },
      "3": {
        "P4": {
          "4": "Layer",
          "5": "Layer"
        }
      },
      "2": {
        "P3": {
          "3": "Layer",
          "6": "Layer"
        }
      }
    },
    "side_loads": [
      3.0,
      1000000.0,
      1000000.0,
      1e-06
    ],
    "excitation": {
      "type": "voltage",
      "value": 1.0
    }
  },
  "settings": {
    "analysis_setup": {
      "adaptive_frequency": 500000.0,
      "frequency_sweep": {
        "frequency_sweep": true,
        "samples": 3,
        "scale": "Logarithmic",
        "start_frequency": 1000.0,
        "stop_frequency": 1000000.0
      },
      "number_passes": 5,
      "percentage_error": 1.0
    },
    "full_model": false,
    "region_offset": 50.0,
    "segmentation_angle": 0.0
  },
  "materials": {
    "material_insulation": {
      "mur": 1,
      "eps_r": 4
    },
    "Copper": {
      "conductivity": 58000000.0,
      "mur": 1,
      "eps_r": 1
    },
    "4F1": {
      "conductivity": 1e-06,
      "power_ferrite_loss_params": {
        "cm": 15.358,
        "x": 1.29,
        "y": 2.181
      },
      "density": 4600,
      "mu(freq)": [
        [0.0, 80.0],
        [984562.393205353, 81.1],
        [2013974.90175465, 82.0],
        [5043159.48717136, 83.0],
        [7101520.60278034, 84.9],
        [8968146.67757928, 86.0],
        [10316051.7838208, 87.0],
        [12433534.237776, 89.0],
        [16197927.8235767, 92.1],
        [19221345.4398991, 94.3],
        [22456979.9553977, 97.7],
        [26648678.3964615, 101.1],
        [29714811.0468401, 106.0],
        [33653251.1825056, 111.0],
        [35814101.0012546, 115.0],
        [38711307.293913, 119.0],
        [42498967.4273376, 123.2],
        [47388796.0971766, 124.7],
        [51222345.2975163, 124.7],
        [55366012.092768, 121.8],
        [58921021.876123, 115.0],
        [62704296.1503099, 108.4],
        [64686076.6154633, 100.0],
        [67776803.2440111, 90.0],
        [74408340.9926387, 70.5],
        [80427654.8305764, 50.3],
        [89681466.7757929, 32.7],
        [103160517.838208, 20.0],
        [113254131.515281, 14.5],
        [124335342.37776, 10.2],
        [145265392.594678, 7.1],
        [161979278.235767, 5.0],
        [177827941.003892, 4.0],
        [204555335.00502, 3.0]
      ]
    },
    "material_bobbin": {
      "mur": 1,
      "eps_r": 4
    },
    "3C81": {
      "conductivity": 1,
      "power_ferrite_loss_params": {
        "cm": 2.55,
        "x": 1.485,
        "y": 2.51
      },
      "density": 4800,
      "mu(freq)": [
        [0.0, 2700.0],
        [100000.0, 2712.0],
        [126152.790334956, 2732.0],
        [159145.265092955, 2750.4],
        [200766.192600726, 2848.0],
        [295700.472126253, 3018.5],
        [396875.882663045, 3200.0],
        [500670.000145919, 3236.7],
        [602933.005246785, 3236.7],
        [796792.598973118, 3089.5],
        [974516.591791268, 2848.0],
        [1328367.9407412, 2448.4],
        [1624659.41566755, 2032.7],
        [2018053.77845186, 1401.0],
        [2430245.92852975, 811.1],
        [2750818.1641727, 509.4],
        [3211637.0354356, 305.3],
        [3692024.49729417, 200.9],
        [4955269.33264953, 81.1],
        [5785379.31607765, 50.9],
        [6967056.41743796, 30.1],
        [7886076.51551497, 21.3]
      ]
    },
    "3F3": {
      "conductivity": 0.5,
      "power_ferrite_loss_params": {
        "cm": 0.195,
        "x": 1.561,
        "y": 2.15
      },
      "density": 4750,
      "mu(freq)": [
        [0.0, 2000.0],
        [98459.6815894695, 2027.2],
        [197983.598439825, 2051.0],
        [398107.170553497, 2100.0],
        [494745.693364606, 2124.0],
        [596047.538592714, 2174.0],
        [696140.064601457, 2251.3],
        [788186.901908786, 2304.4],
        [892404.594894609, 2386.3],
        [994839.015358011, 2500.2],
        [1126381.2001137, 2589.1],
        [1255672.56203026, 2619.4],
        [1378243.15007929, 2619.4],
        [1536444.41791644, 2559.1],
        [1712804.77556574, 2414.3],
        [1822527.78210077, 2251.3],
        [1969618.08128912, 2075.0],
        [2161879.38710699, 1846.9],
        [2372907.99104522, 1550.8],
        [2604535.83467541, 1242.9],
        [2814739.4644536, 1019.6],
        [3287410.45931894, 603.6],
        [3780315.8735092, 300.0],
        [4214238.41031241, 188.3],
        [4625604.95263426, 122.3],
        [4846109.89543321, 100.3],
        [5156553.7681451, 88.3],
        [5402369.31126385, 77.7],
        [5659903.00645773, 70.0],
        [6116695.39929428, 60.1],
        [6713767.41844878, 49.3],
        [7963859.60989012, 39.5],
        [9016877.71231702, 34.3],
        [10209130.7056581, 31.3],
        [11559028.8668147, 28.8]
      ]
    }
  }
}
